=== AEA2002/xml/customers.dtd
<!ELEMENT customers (customer)>
<!ELEMENT customer (note, person, address+)>
<!ELEMENT person (first-name, middle-name?, last-name)>
<!ATTLIST person id CDATA #IMPLIED>
<!ELEMENT address (street1, street2, city, state, postal-code, country)>
<!ATTLIST address type CDATA #IMPLIED>
<!ELEMENT note (#PCDATA)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT middle-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT street1 (#PCDATA)>
<!ELEMENT street2 (#PCDATA)>
<!ELEMENT city    (#PCDATA)>
<!ELEMENT state   (#PCDATA)>
<!ELEMENT postal-code (#PCDATA)>
<!ELEMENT country (#PCDATA)>

=== AEA2002/xml/customers.xml
<?xml version="1.0"?>
<!DOCTYPE customers SYSTEM "customers.dtd">
<customers>
	<customer>
		<note>Our second customer!</note>
		<person id="7">
			<first-name>George</first-name>
			<middle-name>Runyard</middle-name>
			<last-name>Weatherby</last-name>
		</person>
		<address>
			<street1>25 Broadway</street1>
			<street2></street2>
			<city>New York</city>
			<state>NY</state>
			<postal-code>10004</postal-code>
			<country>USA</country>
		</address>
	</customer>
	<customer>
		<note><![CDATA[Jane's last buy was > $1000]]></note>
		<person id="customer1">
			<first-name>Ely</first-name>
			<middle-name>Harvey</middle-name>
			<last-name>Marrero</last-name>
		</person>

		<address type="home">
			<street1>374 Lochness Drive</street1>
			<street2></street2>
			<city>Miami Lakes</city>
			<state>FL</state>
			<postal-code>33014</postal-code>
			<country>US</country>
		</address>

		<address type="billing">
			<street1>10 Monroe Blvd</street1>
			<street2></street2>
			<city>Long Beach</city>
			<state>NY</state>
			<postal-code>11561</postal-code>
			<country>US</country>
		</address>

	</customer>

</customers>
