=== AEA2002/xml/songs.dtd
<!ELEMENT songs (song+)>
<!ELEMENT song (artist, album, date, length, track, title)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT track (#PCDATA)>
<!ELEMENT title (#PCDATA)>

=== AEA2002/xml/songs.xml
<?xml version="1.0"?>
<!DOCTYPE songs SYSTEM "songs.dtd">
<songs>
    <song>
        <artist>Pitbull</artist>
        <album>Globalization</album>
        <date>2014</date>
        <length>3:52</length>
        <track>4</track>
        <title>Fireball</title>
    </song>
</songs>
